-- V1 :: Schema inicial do Sistema Revisional Bancário
-- Espelha as entidades JPA. Hibernate roda em ddl-auto=validate; Flyway é dono do schema.
-- Naming: CamelCaseToUnderscoresNamingStrategy (padrão Spring Boot).

-- ============================================================
-- table_usuario
-- ============================================================
CREATE TABLE table_usuario (
    id_usuario     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf            VARCHAR(11) UNIQUE,
    nome_completo  VARCHAR(100) NOT NULL,
    oab            VARCHAR(100) NOT NULL,
    senha          VARCHAR(100) NOT NULL,
    ativo          BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ============================================================
-- table_caso_revisional
-- FK owner_cpf -> table_usuario.cpf (chave de negócio única)
-- JSONB: contrato, mercado, resultado
-- ============================================================
CREATE TABLE table_caso_revisional (
    id_caso_revisional BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo             VARCHAR(255),
    criado_em          TIMESTAMP,
    atualizado_em      TIMESTAMP,
    owner_cpf          VARCHAR(11) NOT NULL,
    contrato           JSONB,
    mercado            JSONB,
    resultado          JSONB,
    CONSTRAINT fk_caso_usuario
        FOREIGN KEY (owner_cpf) REFERENCES table_usuario (cpf)
);

CREATE INDEX idx_caso_owner_cpf ON table_caso_revisional (owner_cpf);

-- ============================================================
-- table_upload_documento
-- FK case_id -> table_caso_revisional.id_caso_revisional
-- ============================================================
CREATE TABLE table_upload_documento (
    id_upload_documento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_original       VARCHAR(255) NOT NULL,
    caminho_armazenado  VARCHAR(255) NOT NULL,
    hash_sha256         VARCHAR(64),
    criado_em           TIMESTAMP,
    case_id             BIGINT NOT NULL,
    CONSTRAINT fk_documento_caso
        FOREIGN KEY (case_id) REFERENCES table_caso_revisional (id_caso_revisional)
);

CREATE INDEX idx_documento_case_id ON table_upload_documento (case_id);

-- ============================================================
-- table_evento_auditoria
-- FK case_id -> table_caso_revisional.id_caso_revisional
-- ============================================================
CREATE TABLE table_evento_auditoria (
    id_evento_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf_usuario_logado  VARCHAR(11),
    tipo_evento         VARCHAR(255) NOT NULL,
    payload_json        TEXT,
    criado_em           TIMESTAMP,
    case_id             BIGINT NOT NULL,
    CONSTRAINT fk_evento_caso
        FOREIGN KEY (case_id) REFERENCES table_caso_revisional (id_caso_revisional)
);

CREATE INDEX idx_evento_case_id ON table_evento_auditoria (case_id);
