-- V4 :: Multi-tenancy (discriminator). Cada escritório/empresa é um Tenant.
-- Dados de negócio (casos, documentos, eventos) ganham coluna tenant_id que o
-- Hibernate (@TenantId) preenche/filtra automaticamente por requisição.
-- Usuario referencia o tenant (FK), mas NÃO é filtrado: o login é cross-tenant.

-- ============================================================
-- table_tenant
-- ============================================================
CREATE TABLE table_tenant (
    id_tenant     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    cnpj          VARCHAR(14) UNIQUE,
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    data_criacao  TIMESTAMP
);

-- Tenant padrão (id=1) para acolher dados pré-existentes e o admin seed.
INSERT INTO table_tenant (id_tenant, nome, ativo, data_criacao)
VALUES (1, 'MPG Sistemas', TRUE, now());

-- Avança a sequência de IDENTITY para não colidir com inserts futuros do JPA.
SELECT setval(pg_get_serial_sequence('table_tenant', 'id_tenant'),
              (SELECT MAX(id_tenant) FROM table_tenant));

-- ============================================================
-- table_usuario.tenant_id  (FK simples; sem @TenantId)
-- ============================================================
ALTER TABLE table_usuario ADD COLUMN tenant_id BIGINT;
UPDATE table_usuario SET tenant_id = 1 WHERE tenant_id IS NULL;
ALTER TABLE table_usuario
    ALTER COLUMN tenant_id SET NOT NULL,
    ADD CONSTRAINT fk_usuario_tenant FOREIGN KEY (tenant_id) REFERENCES table_tenant (id_tenant);

-- ============================================================
-- table_caso_revisional.tenant_id  (discriminator @TenantId)
-- ============================================================
ALTER TABLE table_caso_revisional ADD COLUMN tenant_id BIGINT;
UPDATE table_caso_revisional c
    SET tenant_id = u.tenant_id
    FROM table_usuario u
    WHERE c.owner_cpf = u.cpf;
UPDATE table_caso_revisional SET tenant_id = 1 WHERE tenant_id IS NULL;
ALTER TABLE table_caso_revisional
    ALTER COLUMN tenant_id SET NOT NULL,
    ADD CONSTRAINT fk_caso_tenant FOREIGN KEY (tenant_id) REFERENCES table_tenant (id_tenant);
CREATE INDEX idx_caso_tenant ON table_caso_revisional (tenant_id);

-- ============================================================
-- table_upload_documento.tenant_id  (discriminator @TenantId)
-- ============================================================
ALTER TABLE table_upload_documento ADD COLUMN tenant_id BIGINT;
UPDATE table_upload_documento d
    SET tenant_id = c.tenant_id
    FROM table_caso_revisional c
    WHERE d.case_id = c.id_caso_revisional;
UPDATE table_upload_documento SET tenant_id = 1 WHERE tenant_id IS NULL;
ALTER TABLE table_upload_documento
    ALTER COLUMN tenant_id SET NOT NULL,
    ADD CONSTRAINT fk_documento_tenant FOREIGN KEY (tenant_id) REFERENCES table_tenant (id_tenant);
CREATE INDEX idx_documento_tenant ON table_upload_documento (tenant_id);

-- ============================================================
-- table_evento_auditoria.tenant_id  (discriminator @TenantId)
-- ============================================================
ALTER TABLE table_evento_auditoria ADD COLUMN tenant_id BIGINT;
UPDATE table_evento_auditoria e
    SET tenant_id = c.tenant_id
    FROM table_caso_revisional c
    WHERE e.case_id = c.id_caso_revisional;
UPDATE table_evento_auditoria SET tenant_id = 1 WHERE tenant_id IS NULL;
ALTER TABLE table_evento_auditoria
    ALTER COLUMN tenant_id SET NOT NULL,
    ADD CONSTRAINT fk_evento_tenant FOREIGN KEY (tenant_id) REFERENCES table_tenant (id_tenant);
CREATE INDEX idx_evento_tenant ON table_evento_auditoria (tenant_id);
