-- V5 :: Configuração operacional (OCR + IA) por tenant.
-- Antes: linha única global (id=1). Agora: 1 linha por escritório (@TenantId),
-- cada tenant com sua própria chave OpenRouter (isola custo/billing de IA).
-- A linha global existente passa a pertencer ao tenant 1 (MPG Sistemas).

-- id vira IDENTITY (novas linhas são criadas sob demanda pelo JPA)
ALTER TABLE table_configuracao_sistema
    ALTER COLUMN id_configuracao_sistema ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('table_configuracao_sistema', 'id_configuracao_sistema'),
              GREATEST((SELECT COALESCE(MAX(id_configuracao_sistema), 1) FROM table_configuracao_sistema), 1));

-- discriminator tenant_id (1 configuração por escritório)
ALTER TABLE table_configuracao_sistema ADD COLUMN tenant_id BIGINT;
UPDATE table_configuracao_sistema SET tenant_id = 1 WHERE tenant_id IS NULL;
ALTER TABLE table_configuracao_sistema
    ALTER COLUMN tenant_id SET NOT NULL,
    ADD CONSTRAINT fk_configuracao_tenant FOREIGN KEY (tenant_id) REFERENCES table_tenant (id_tenant),
    ADD CONSTRAINT uq_configuracao_tenant UNIQUE (tenant_id);
